# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        script: |
          cd ${{ secrets.REMOTE_TARGET }}
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm i
          npm run build
          pm2 restart 10
